export const GET_ERRORS = "GET_ERRORS";
export const GET_ERROR="GET_ERROR"
export const GET_EMPLOYEES="GET_EMPLOYEES";
export const GET_EMPLOYEE ="GET_EMPLOYEE";
export const GET_MANAGERS = "GET_MANAGERS";
export const GET_MANAGER = "GET_MANAGER";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const DELETE_MANAGER = "DELETE_MANAGER";

export const GET_TIMECARDS = "GET_TIMECARDS";
export const GET_TIMECARD = "GET_TIMECARD";
export const DELETE_TIMECARD ="DELETE_TIMECARD";
